#!/bin/sh

case "$1" in
    start)
        echo "Starting aesdsocket"
        start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -- -d
        ;;
    stop)
        echo "Stoppingaesdsocket"
        start-stop-daemon -K -n aesdsocket -s TERM
        sleep 1
        ;;
    *)
        echo "Default: $0 {start|stop}"

    exit 1
esac

exit 0
