#!/bin/sh

case "$1" in
    start)
        echo "Starting aesdsocket"
        start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -- -d
        ;;
    stop)
        echo "Stoppingaesdsocket"
        while start-stop-daemon -K -t -n aesdsocket > /dev/null 2>&1; do
            sleep 1
        done
        ;;
    *)
        echo "Default: $0 {start|stop}"

    exit 1
esac

exit 0
